spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/uneasySolver
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  profiles:
    include: SECRET





logging:
  level:
    org.hibernate.SQL: debug

